
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.MonoGameContent
{
	public partial class MonoGameOptions
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.CheckButton chkCompress;
		private global::Gtk.ComboBox cmbPlatforms;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.MonoGameContent.MonoGameOptions
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.MonoGameContent.MonoGameOptions";
			// Container child MonoDevelop.MonoGameContent.MonoGameOptions.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Platform");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w1.X = 6;
			w1.Y = 24;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Compress Content");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w2.X = 5;
			w2.Y = 59;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.chkCompress = new global::Gtk.CheckButton ();
			this.chkCompress.CanFocus = true;
			this.chkCompress.Name = "chkCompress";
			this.chkCompress.Label = "";
			this.chkCompress.Active = true;
			this.chkCompress.DrawIndicator = true;
			this.chkCompress.UseUnderline = true;
			this.fixed1.Add (this.chkCompress);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.chkCompress]));
			w3.X = 134;
			w3.Y = 58;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cmbPlatforms = global::Gtk.ComboBox.NewText ();
			this.cmbPlatforms.WidthRequest = 200;
			this.cmbPlatforms.Name = "cmbPlatforms";
			this.fixed1.Add (this.cmbPlatforms);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.cmbPlatforms]));
			w4.X = 133;
			w4.Y = 21;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
