# Repo: codefoco/AzureDevopsTemplates
resources:
  repositories:
    - repository: templates
      type: github
      name: codefoco/AzureDevopsTemplates
      endpoint: codefoco

pool:
  vmImage: 'macOS-10.14'
  demands: msbuild

steps:
- checkout: self
  submodules: 'true'

- template: common-dotnet.yml@templates
- template: common-macos.yml@templates

- task: NuGetCommand@2 #MonoGame.Framework/MonoGame.Framework.iOSCore.csproj
  displayName: 'NuGet restore  MonoGame.Framework/MonoGame.Framework.iOSCore.csproj'
  inputs:
    restoreSolution: ./MonoGame.Framework/MonoGame.Framework.iOSCore.csproj

- task: PowerShell@2
  displayName: 'PreBuild Codefoco.MonoGame.Framework'
  inputs:
    targetType: filePath
    filePath: ./devops/PreBuild.ps1
    arguments: 'Codefoco.MonoGame.Framework Codefoco.MonoGame.Framework.nuspec'

# Build  MonoGame

- task: MSBuild@1 # Fantas.MonoGame.sln
  displayName: 'Build csproj ./MonoGame.Framework/MonoGame.Framework.iOSCore.csproj'
  inputs:
    solution: ./MonoGame.Framework/MonoGame.Framework.iOSCore.csproj
    configuration: Release

- task: PublishBuildArtifacts@1 
  displayName: 'Publish Artifact: MonoGame.Frawework.dll'
  inputs:
    PathtoPublish: ./MonoGame.Framework/bin/iOSCore/Release/xamarinios10/MonoGame.Framework.dll
    ArtifactName: Xamarin.iOS.MonoGame.Framework.dll

- task: PublishBuildArtifacts@1 
  displayName: 'Publish Artifact: MonoGame.Frawework.pdb'
  inputs:
    PathtoPublish: ./MonoGame.Framework/bin/iOSCore/Release/xamarinios10/MonoGame.Framework.pdb
    ArtifactName: Xamarin.iOS.MonoGame.Framework.pdb

- task: PublishBuildArtifacts@1 
  displayName: 'Publish Artifact: MonoGame.Frawework.xml'
  inputs:
    PathtoPublish: ./MonoGame.Framework/bin/iOSCore/Release/xamarinios10/MonoGame.Framework.xml
    ArtifactName: Xamarin.iOS.MonoGame.Framework.xml

- task: PublishBuildArtifacts@1 
  displayName: 'Publish Artifact: MonoGame.Frawework.dll'
  inputs:
    PathtoPublish: ./MonoGame.Framework/bin/iOSCore/Release/xamarintvos10/MonoGame.Framework.dll
    ArtifactName: Xamarin.tvOS.MonoGame.Framework.dll

- task: PublishBuildArtifacts@1 
  displayName: 'Publish Artifact: MonoGame.Frawework.pdb'
  inputs:
    PathtoPublish: ./MonoGame.Framework/bin/iOSCore/Release/xamarintvos10/MonoGame.Framework.pdb
    ArtifactName: Xamarin.tvOS.MonoGame.Framework.pdb

- task: PublishBuildArtifacts@1 
  displayName: 'Publish Artifact: MonoGame.Frawework.xml'
  inputs:
    PathtoPublish: ./MonoGame.Framework/bin/iOSCore/Release/xamarintvos10/MonoGame.Framework.xml
    ArtifactName: Xamarin.tvOS.MonoGame.Framework.xml

- task: TriggerBuild@3
  displayName: 'Trigger a new build of Codefoco.MonoGame.Windows'
  inputs:
    buildDefinition: 'Codefoco.MonoGame.Framework.Windows'
    ignoreSslCertificateErrors: true
    useSameSourceVersion: true
    password: '$(myToken)'

- template: send-telegram.yml@templates
