#!/bin/sh
xdg-mime install /tmp/mgcb.xml --novendor
xdg-mime default "Monogame Pipeline.desktop" text/mgcb
sudo -H -u $SUDO_USER bash -c 'mdtool setup install /tmp/MonoDevelop.MonoGame.mpack'

if [ -L /usr/lib/mono/xbuild/MonoGame/v3.0/Tools ]; then
	rm -rf /usr/lib/mono/xbuild/MonoGame/v3.0/Tools
fi
ln -s /opt/monogame-pipeline /usr/lib/mono/xbuild/MonoGame/v3.0/Tools

if [ -f /usr/share/applications/Monogame\ Pipeline.desktop ]
then
	rm /usr/share/applications/Monogame\ Pipeline.desktop
fi
echo "[Desktop Entry]\nVersion=1.0\nEncoding=UTF-8\nName=MonoGame Pipeline\nGenericName=MonoGame Pipeline\nComment=Used to create platform specific .xnb files\nExec=monogame-pipeline %F\nTryExec=monogame-pipeline\nIcon=monogame\nStartupNotify=true\nTerminal=false\nType=Application\nMimeType=text/mgcb;\nCategories=Development;" >> /usr/share/applications/Monogame\ Pipeline.desktop

