<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!-- x64 -->
    <Content Include="..\..\..\Artifacts\native\mgruntime\desktopvk\windows\x64\Release\mgruntime.dll"
      Condition="Exists('..\..\..\Artifacts\native\mgruntime\desktopvk\windows\x64\Release\mgruntime.dll')">
      <PackagePath>runtimes\win-x64\native</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <!-- arm64 -->
    <Content Include="..\..\..\Artifacts\native\mgruntime\desktopvk\windows\arm64\Release\mgruntime.dll"
      Condition="Exists('..\..\..\Artifacts\native\mgruntime\desktopvk\windows\arm64\Release\mgruntime.dll')">
      <PackagePath>runtimes\win-arm64\native</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>