<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <DefineConstants>WEB;XNADESIGNPROVIDED;NATIVE;NETSTANDARD;STBSHARP_INTERNAL</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>The MonoGame browser platform.</Description>
    <PackageTags>monogame;.net core;core;.net standard;standard;web;webgl2</PackageTags>
    <PackageId>MonoGame.Framework.Web</PackageId>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <CopyContentFiles>True</CopyContentFiles>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**\*" />
    <Compile Remove="obj\**\*" />
    <Compile Remove="Platform\**\*" />
    <Compile Remove="Properties\**\*" />
    <Compile Remove="Utilities\System.Numerics.Vectors\**\*" />
    <Compile Remove="Devices\**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Platform\**\*" />
    <None Remove="Utilities\System.Numerics.Vectors\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Platform\Native\**\*" />
    <Compile Include="Platform\Properties\AssemblyInfo.Web.cs" />
    <Compile Include="Platform\TitleContainer.Web.cs" />
    <Compile Include="Platform\GraphicsDeviceManager.Web.cs" />
    <Compile Include="Platform\Graphics\GraphicsAdapter.Web.cs" />
    <Compile Include="Platform\Graphics\GraphicsDevice.Web.cs" />
    <Compile Include="Platform\Audio\DynamicSoundEffectInstance.Default.cs" />
    <Compile Include="Platform\Audio\Microphone.Default.cs" />
    <Compile Include="Platform\Audio\SoundEffect.Web.cs" />
    <Compile Include="Platform\Audio\SoundEffectInstance.Default.cs" />
    <Compile Include="Platform\Input\GamePad.Web.cs" />
    <Compile Include="Platform\Input\Mouse.Web.cs" />
    <Compile Include="Platform\Media\MediaLibrary.Default.cs" />
    <Compile Include="Platform\Media\MediaPlayer.Default.cs" />
    <Compile Include="Platform\Media\Song.Default.cs" />
    <Compile Include="Platform\Media\Video.Default.cs" />
    <Compile Include="Platform\Media\VideoPlayer.Default.cs" />
    <Compile Include="Platform\Web\**\*.cs" />
    <Compile Include="Platform\Input\InputKeyEventArgs.cs" />
    <Compile Include="Platform\Utilities\AssemblyHelper.cs" />
    <Compile Include="Platform\Utilities\ReflectionHelpers.Default.cs" />
    <Compile Include="Platform\Threading.cs" />
    <Compile Include="Platform\Desktop\Devices\Sensors\Accelerometer.cs" />
    <Compile Include="Platform\Desktop\Devices\Sensors\Compass.cs" />
    <Compile Include="..\ThirdParty\StbImageSharp\src\**\*.cs" LinkBase="Utilities\StbImageSharp" />
    <Compile Include="..\ThirdParty\StbImageWriteSharp\src\**\*.cs" LinkBase="Utilities\StbImageWriteSharp" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Platform\Native\DynamicSoundEffectInstance.Native.cs" />
    <Compile Remove="Platform\Native\GamePlatform.Native.cs" />
    <Compile Remove="Platform\Native\GamePad.Native.cs" />
    <Compile Remove="Platform\Native\GameWindow.Native.cs" />
    <Compile Remove="Platform\Native\GraphicsAdapter.Native.cs" />
    <Compile Remove="Platform\Native\GraphicsDevice.Native.cs" />
    <Compile Remove="Platform\Native\GraphicsDeviceManager.Native.cs" />
    <Compile Remove="Platform\Native\MediaLibrary.Native.cs" />
    <Compile Remove="Platform\Native\MediaPlayer.Native.cs" />
    <Compile Remove="Platform\Native\Microphone.Native.cs" />
    <Compile Remove="Platform\Native\Mouse.Native.cs" />
    <Compile Remove="Platform\Native\PlatformInfo.Native.cs" />
    <Compile Remove="Platform\Native\Song.Native.cs" />
    <Compile Remove="Platform\Native\SoundEffect.Native.cs" />
    <Compile Remove="Platform\Native\SoundEffectInstance.Native.cs" />
    <Compile Remove="Platform\Native\TitleContainer.Native.cs" />
    <Compile Remove="Platform\Native\Video.Native.cs" />
    <Compile Remove="Platform\Native\VideoPlayer.Native.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Platform\Web\Host\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Import Project="MonoGame.Framework.Devices.Sensors.targets" />
</Project>
