
// This file has been generated by the GUI designer. Do not modify.
namespace MonoGame.Tools.Pipeline
{
	public partial class NewTemplateDialog
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry entry1;
		
		private global::Gtk.Label label2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoGame.Tools.Pipeline.NewTemplateDialog
			this.WidthRequest = 340;
			this.Name = "MonoGame.Tools.Pipeline.NewTemplateDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child MonoGame.Tools.Pipeline.NewTemplateDialog.VBox
            #if GTK2
			global::Gtk.VBox w1 = this.VBox;
            #elif GTK3
            global::Gtk.Box w1 = this.ContentArea;
            #endif
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
            #if GTK3
            this.treeview1.Expand = true;
            #endif
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.treeview1.HeadersVisible = false;
			this.GtkScrolledWindow.Add (this.treeview1);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Name:");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.hbox1.Add (this.entry1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry1]));
			w5.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";

            #if GTK3
            if(Global.GtkMajorVersion == 3 && Global.GtkMinorVersion >= 8)
                Gtk3Wrapper.gtk_widget_set_opacity(label2.Handle, 0.7);
            #endif

			this.vbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));

            this.BorderWidth = 3;
            this.vbox2.Spacing = 3;
            w1.Spacing = 3;

            if (Global.UseHeaderBar)
            {
                w3.Position = 2;
                w6.Position = 0;
                w7.Position = 1;
            }
            else
            {
                w3.Position = 0;
                w6.Position = 1;
                w7.Position = 2;
            }

			w7.Expand = false;
			w7.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w8.Position = 0;

			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 340;
            this.DefaultHeight = ((Global.UseHeaderBar) ? 32 : 0) + 352;
            this.label2.Hide ();

            #if GTK3
            Gdk.Geometry geom = new Gdk.Geometry();
            geom.MinWidth = this.DefaultWidth;
            geom.MinHeight = 200;
            this.SetGeometryHints(this, geom, Gdk.WindowHints.MinSize);
            #endif

			this.Show ();
			this.Response += new global::Gtk.ResponseHandler (this.OnResponse);
			this.treeview1.CursorChanged += new global::System.EventHandler (this.OnTreeview1CursorChanged);
			this.entry1.Changed += new global::System.EventHandler (this.OnEntry1Changed);
		}
	}
}
