
// This file has been generated by the GUI designer. Do not modify.
namespace MonoGame.Tools.Pipeline
{
	public partial class TextEditorDialog
	{
		private global::Gtk.Label label2;
		
		private global::Gtk.Entry entry1;
		
		private global::Gtk.Label label3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoGame.Tools.Pipeline.TextEditorDialog
			this.Name = "MonoGame.Tools.Pipeline.TextEditorDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(4));
			// Internal child MonoGame.Tools.Pipeline.TextEditorDialog.VBox
            #if GTK2
			global::Gtk.VBox w1 = this.VBox;
            #elif GTK3
            global::Gtk.Box w1 = this.ContentArea;
            #endif
			w1.Name = "dialog1_VBox";
			w1.Spacing = 4;
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			w1.Add (this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.label2]));
			w2.Position = 0;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
            #if GTK3
            entry1.Expand = true;
            #endif
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			w1.Add (this.entry1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1 [this.entry1]));
			w3.Position = 1;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.HeightRequest = 0;
			this.label3.Name = "label3";

            #if GTK3
            if(Global.GtkMajorVersion == 3 && Global.GtkMinorVersion >= 8)
                Gtk3Wrapper.gtk_widget_set_opacity(label3.Handle, 0.7);
            #endif

			w1.Add (this.label3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.label3]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 367;
			this.DefaultHeight = 143;
            this.label3.Hide ();

            #if GTK3
            Gdk.Geometry geom = new Gdk.Geometry();
            geom.MinWidth = this.DefaultWidth;
            geom.MinHeight = this.DefaultHeight;
            geom.MaxWidth = 1000;
            geom.MaxHeight = this.DefaultHeight;
            this.SetGeometryHints(this, geom, Gdk.WindowHints.MinSize | Gdk.WindowHints.MaxSize);
            #endif

			this.Show ();
			this.Response += new global::Gtk.ResponseHandler (this.OnResponse);
			this.entry1.Changed += new global::System.EventHandler (this.OnEntry1Changed);
            this.entry1.Activated += OnEntry1Activated;
		}
	}
}
