name: Feature Request
description: Propose a feature be added or removed from MonoGame.
title: "[Feature Request]: "
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to submit this feature request.
      Please note that feature requests will be reviewed and discussed, which takes time, before approved or denied.
      Please use the following template to help us gather the information we need to start this process.
- type: textarea
  id: purpose
  validations:
    required: true
  attributes:
    label: Purpose
    description: Please describe the purpose of this new feature.
    placeholder: Purpose
- type: textarea
  id: motivation
  validations:
    required: true
  attributes:
    label: Motivation
    description: Please describe the motivation for wanting this feature to be implemented.  How does it benefit the users of MonoGame?
    placeholder: Motivation
