<Project>
  <Target Name="BuildContent" BeforeTargets="AssignTargetPaths;ResolveCurrentProjectStaticWebAssetsInputs">
    <PropertyGroup>
      <ContentOutput>$(ProjectDir)$(OutputPath)</ContentOutput>
      <ContentTemp>$(ProjectDir)$(IntermediateOutputPath)</ContentTemp>
      <ContentArgs>build -p $(MonoGamePlatform) -s Content/Assets -o $(ContentOutput) -i $(ContentTemp)</ContentArgs>
      <ContentCommand>$(MSBuildThisFileDirectory)bin\Debug\Content</ContentCommand>
    </PropertyGroup>
    <MSBuild Projects="$(MSBuildThisFileDirectory)Content.csproj" Targets="Build" RemoveProperties="Configuration;TargetFramework;RuntimeIdentifier;RuntimeIdentifiers" />
    <Exec Command="$(ContentCommand) $(ContentArgs)" WorkingDirectory="$(MSBuildThisFileDirectory)..\" CustomErrorRegularExpression="\[E\] .+" CustomWarningRegularExpression="\[W\] .+" />
   </Target>
  <Target Name="AddGeneratedContentAssets"
    DependsOnTargets="BuildContent"
    BeforeTargets="AssignTargetPaths;ResolveCurrentProjectStaticWebAssetsInputs">
    <ItemGroup>
      <GeneratedAsset Include="$(ProjectDir)$(OutputPath)Content\**\*" />

      <AndroidAsset Include="@(GeneratedAsset)"
        Condition="'$(MonoGamePlatform)' == 'Android'">
        <Link>Content\%(GeneratedAsset.RecursiveDir)%(GeneratedAsset.Filename)%(GeneratedAsset.Extension)</Link>
      </AndroidAsset>

      <BundledResource Include="@(GeneratedAsset)"
        Condition="'$(MonoGamePlatform)' == 'MacOSX' Or '$(MonoGamePlatform)' == 'iOS'">
        <Link>Content\%(GeneratedAsset.RecursiveDir)%(GeneratedAsset.Filename)%(GeneratedAsset.Extension)</Link>
      </BundledResource>
    </ItemGroup>

    <ItemGroup Condition="'$(MonoGamePlatform)' == 'WebGL2'">
      <GeneratedWebContentDirectory Include="@(GeneratedAsset->'$(ProjectDir)wwwroot\Content\%(RecursiveDir)')" />
      <GeneratedWebContentFile Include="@(GeneratedAsset)">
        <DestinationPath>$(ProjectDir)wwwroot\Content\%(RecursiveDir)%(Filename)%(Extension)</DestinationPath>
      </GeneratedWebContentFile>
    </ItemGroup>

    <MakeDir
      Directories="@(GeneratedWebContentDirectory)"
      Condition="'$(MonoGamePlatform)' == 'WebGL2'" />

    <Copy
      SourceFiles="@(GeneratedWebContentFile)"
      DestinationFiles="@(GeneratedWebContentFile->'%(DestinationPath)')"
      SkipUnchangedFiles="true"
      Condition="'$(MonoGamePlatform)' == 'WebGL2'" />
  </Target>
</Project>
