
//================================================================================
//
//  Copyright (c) objectnation GmbH
//
//================================================================================
//
//  Author          simon.wilson
//  Creation Date   13.09.2002
//  Creation Time   16:47:52
//  IDE Version     Microsoft Development Environment Enterprise Edition 7.00
//  OS Version      Microsoft Windows NT 5.1.2600.0
//
//================================================================================

#region Copyright � objectnation GmbH

// This software is provided 'as-is'. While the greatest care has been taken to 
// ensure that the software functions correctly, no guarantee can be made to this effect.
//
// objectnation grants permission to anyone to use this software for any purpose as long as 
// it is in compliance with the following restrictions:
//
// 1.	This software is the intellectual property and copyright of objectnation GmbH. 
//    Under no circumstances may the origin of the software be misrepresented.
//
// 2.	Should this software be used in the development of a commercial product, 
//    then an acknowledgement in that product's documentation is a requirement. 
//    The following text should be used:
//
//    This product contains code generated by objectnation SP/Invoke, 
//    copyright � objectnation GmbH (http://www.objectnation.com).
//
// 3.	The software may not be redistributed without the express written permission of 
//    the copyright holder, namely objectnation GmbH, Switzerland.

#endregion

namespace Microsoft.VisualStudio.Extensibility {

    using System;
    using System.Runtime.InteropServices;

    [
        ComImport,
        Guid("FC4801A3-2BA9-11CF-A229-00AA003D7352"), 
        InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)
    ]
    internal interface IObjectWithSite {

        //
        //    HRESULT SetSite(
        //				[in] IUnknown * pUnkSite);
        //
        void SetSite(
            [MarshalAs(UnmanagedType.Interface)] object pUnkSite);

        //
        // HRESULT GetSite(
        //        [in] REFIID riid,
        //        [out, iid_is(riid)] void ** ppvSite);
        //
        void GetSite(                          [In] ref Guid riid,
            [Out, MarshalAs(UnmanagedType.LPArray)] object[] ppvSite);
    }
}
