'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

<Assembly: [global].Android.Runtime.ResourceDesignerAttribute("BlankApp.Android.Resource", IsApplication:=True)>
Namespace BlankApp.Android	
	
	<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>
	Partial Public Class Resource

        Private Shared Sub New()
            Global.Android.Runtime.ResourceIdManager.UpdateIdValues()
        End Sub

        Public Shared Sub UpdateIdValues()
        End Sub
				
		Public Partial Class Attribute
            Private Shared Sub New()
                Global.Android.Runtime.ResourceIdManager.UpdateIdValues()
            End Sub

            Private Sub New()
            End Sub
        End Class
		
		public partial class Drawable
			
			' aapt resource value: 0x7f020000
			public const Icon As Integer = 2130837504
			
			' aapt resource value: 0x7f020001
			public const Splash As integer = 2130837505
			
			Private Shared Sub New()
                Global.Android.Runtime.ResourceIdManager.UpdateIdValues()
            End Sub

            Private Sub New()
            End Sub
		end class
		
		public partial class [String]
			
			' aapt resource value: 0x7f030001
			public const ApplicationName As integer = 2130903041
			
			' aapt resource value: 0x7f030000
			public const Hello As integer = 2130903040
			
			Private Shared Sub New()
                Global.Android.Runtime.ResourceIdManager.UpdateIdValues()
            End Sub

            Private Sub New()
            End Sub
		end class
		
		public partial class Style 
			
			' aapt resource value: 0x7f040000
			public const Theme_Splash As integer = 2130968576
			
			Private Shared Sub New()
                Global.Android.Runtime.ResourceIdManager.UpdateIdValues()
            End Sub

            Private Sub New()
            End Sub
		end class
	end class
end namespace
