#!/bin/bash
#mgcb terminal command
if [ -f /usr/local/bin/mgcb ]
then
	rm /usr/local//bin/mgcb
fi
echo "#!/bin/bash
mono /Applications/Pipeline.app/Contents/MonoBundle/MGCB.exe \"\$@\"" >> /usr/local/bin/mgcb
chmod u+x /usr/local/bin/mgcb
#write an uninstaller
if [ -f /usr/local/bin/monogame-uninstall ]
then
	rm /usr/local/bin/monogame-uninstall
fi
echo "#!/bin/bash

sudo rm -Rf '/Applicatons/Pipeline.app/'
sudo pkgutil --forget com.monogame.pipeline
if [ -d '/Applications/Xamarin Studio.app' ]
then
  /Applications/Xamarin\ Studio.app/Contents/MacOS/mdtool setup uninstall MonoDevelop.MonoGame -y
fi
sudo rm /usr/local/bin/mgcb
sudo rm /usr/local/bin/monogame-uninstall
" >> /usr/local/bin/monogame-uninstall
chmod +x /usr/local/bin/monogame-uninstall
