#!/bin/bash
if [ -d "/Applications/Xamarin Studio.app" ]
then
	CONSOLE_USER=$(stat -f '%Su' /dev/console)
	sudo -u $CONSOLE_USER /Applications/Xamarin\ Studio.app/Contents/MacOS/mdtool setup install /tmp/MonoDevelop.MonoGame_*.mpack -y
fi
sudo rm /tmp/MonoDevelop.MonoGame_*.mpack
