
// This file has been generated by the GUI designer. Do not modify.
namespace MonoGame.Tools.Pipeline
{
	public partial class PropertiesView
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button button15;
		
		private global::Gtk.Button button2;
		
		private global::Gtk.VPaned vpaned1;
		
		private global::MonoGame.Tools.Pipeline.PropertyGridTable propertygridtable1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textview1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoGame.Tools.Pipeline.PropertiesView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoGame.Tools.Pipeline.PropertiesView";
			// Container child MonoGame.Tools.Pipeline.PropertiesView.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button15 = new global::Gtk.Button ();
			this.button15.CanFocus = true;
			this.button15.Name = "button15";
			this.button15.UseUnderline = true;
			this.button15.FocusOnClick = false;
			this.button15.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button15.Label = global::Mono.Unix.Catalog.GetString ("Group");
			this.hbox1.Add (this.button15);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button15]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.FocusOnClick = false;
			this.button2.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("ABC");
			this.hbox1.Add (this.button2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button2]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 247;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.propertygridtable1 = new global::MonoGame.Tools.Pipeline.PropertyGridTable ();
			this.propertygridtable1.Events = ((global::Gdk.EventMask)(256));
			this.propertygridtable1.Name = "propertygridtable1";
			this.vpaned1.Add (this.propertygridtable1);
			global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.propertygridtable1]));
			w4.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.GtkScrolledWindow.Add (this.textview1);
			this.vpaned1.Add (this.GtkScrolledWindow);
			this.vbox2.Add (this.vpaned1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vpaned1]));
			w7.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.button15.Clicked += new global::System.EventHandler (this.OnButton15Clicked);
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
			this.textview1.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.OnTextview1SizeAllocated);
		}
	}
}
