
// This file has been generated by the GUI designer. Do not modify.
namespace MonoGame.Tools.Pipeline
{
	public partial class PropertiesView
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.VPaned vpaned1;
		
		private global::Gtk.ScrolledWindow scrolledwindow2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoGame.Tools.Pipeline.PropertiesView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoGame.Tools.Pipeline.PropertiesView";
			// Container child MonoGame.Tools.Pipeline.PropertiesView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 259;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.WidthRequest = 100;
			this.scrolledwindow2.HeightRequest = 100;
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			this.scrolledwindow2.BorderWidth = ((uint)(2));
			this.vpaned1.Add (this.scrolledwindow2);
			global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.scrolledwindow2]));
			w1.Resize = false;
			this.vbox1.Add (this.vpaned1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vpaned1]));
			w2.Position = 0;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.vbox1.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.OnVbox1SizeAllocated);
		}
	}
}
