name: Build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Disable annotations
        run: echo "::remove-matcher owner=csc::"

      - name: Install required workloads
        run:   |
              if [ "$RUNNER_OS" == "Linux" ]; then
                    echo "MICROSOFT SUPPORT ANDROID WORKLOAD ON LINUX PLZZZ!"
              elif [ "$RUNNER_OS" == "Windows" ]; then
                    dotnet.exe workload install android ios macos
              else
                    dotnet workload install android ios macos
              fi
        shell: bash

      - name: Run MonoGame.Framework.Build
        run: dotnet run --project build/MonoGame.Framework.Build.csproj -- --target=Default

      - name: Package nuget artifacts
        uses: actions/upload-artifact@main
        with:
          name: nuget-${{ matrix.os }}
          path: |
            Artifacts/NuGet/*.nupkg
          if-no-files-found: error

      - name: Package Visual Studio extension artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@main
        with:
          name: Visual Studio Extension
          path: |
            Artifacts/MonoGame.Templates.VSExtension/*.vsix
          if-no-files-found: error
