name: Build And Deploy

on:
  push:
    branches:
      develop

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Disable annotations
        run: echo "::remove-matcher owner=csc::"

      - name: Install required workloads
        run:   |
              if [ "$RUNNER_OS" == "Linux" ]; then
                    echo "MICROSOFT SUPPORT ANDROID WORKLOAD ON LINUX PLZZZ!"
              elif [ "$RUNNER_OS" == "Windows" ]; then
                    dotnet.exe workload install android ios macos
              else
                    dotnet workload install android ios macos
              fi
        shell: bash

      - name: Run MonoGame.Framework.Build
        run: dotnet run --project build/MonoGame.Framework.Build.csproj -- --target=Default

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Upload Artifacts
        run: dotnet run --project build/MonoGame.Framework.Build.csproj -- --target=UploadArtifacts
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ env.ACTIONS_RUNTIME_TOKEN }}
          ACTIONS_RUNTIME_URL: "${{ env.ACTIONS_RUNTIME_URL }}"

  deploy:
      name: Deploy
      needs: [ build ]
      runs-on: ubuntu-latest
      permissions:
          packages: write
          contents: write
      steps:
          - name: Expose GitHub Runtime
            uses: crazy-max/ghaction-github-runtime@v3

          - name: Clone Repository
            uses: actions/checkout@v4

          - name: Setup .NET ${{ matrix.dotnet-version }}
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: '8.0.x'

          - name: Push GitHub Nugets
            run: dotnet run --project build/MonoGame.Framework.Build.csproj -- --target=DeployNuGetsToGithub
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
